codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: up
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

D2 = z 1(00) = SO
D9 z=0.5 D11= z = 1.5 
D4=-z^2 . d^2(2)/ D9 + D11(cc) 
D3 = -w0^(z+1) . -pK(u) - Kab 
TGS = -Q 
S=~Q

clozapina (short) 2p^2=expt^-1 
behistina y/o dogmatil = - Kab
